#!/bin/sh
WHERE="application_guitar_pro5-37697380.gp5"
set -e
rm -f generated-*
VLYRICS=`cat vocaloid_lyrics`
java -jar ../../guitarproToLy/1.jar < song.gp5 \
add-lyrics vocaloid 0 1 "$VLYRICS" \
modified-filename drs \
track 0 \
    preset kav \
    output-lilypond \
    output-dotext \
    output-lyrics \
    which-lyrics text \
    output-karaoke \
track 0 \
    preset vocaloid \
    which-lyrics vocaloid \
    output-lilypond \
    output-vocaloid \
track 0 \
    preset susan \
    layout-extra '\clef "treble_8"' \
    output-lilypond \
track 2 \
    preset peter \
    output-chords \
    output-lilypond \
track 3 \
    preset bass \
    output-lilypond \
    output-dotext \
track 1 \
    preset midiOne \
    output-lilypond \
    output-dotext \
track 4 \
    preset gg \
    output-drums \
2>&1|tee log
