#!/bin/sh
WHERE="/share/mirror/songsterr/stuff/d-keep/d-Foo Fighters/d-Big Me-s7725/d-r358016/application_guitar_pro5-37697380.gp5"
set -e
rm -f generated-*
java -jar ../../guitarproToLy/1.jar <"$WHERE" \
modified-filename drs \
track 0 \
    preset kav \
    output-lilypond \
    output-dotext \
    output-lyrics \
    which-lyrics 0 \
    output-karaoke \
track 0 \
    preset susan \
    use-bend-end \
    output-lilypond \
track 2 \
    preset peter \
    output-chords \
    output-lilypond \
track 3 \
    preset bass \
    output-lilypond \
    output-dotext \
track 1 \
    preset midiOne \
    output-lilypond \
    output-dotext \
track 3 \
    preset gg \
    output-drums \
2>&1|tee log
