#!/bin/sh
java -jar ../../guitarproToLy/1.jar < song.gp5 \
track 0 preset peter output-lilypond \
track 1 preset bass output-lilypond \
track 4 preset kav output-lilypond output-lyrics output-karaoke \
track 2 preset gg output-drums \
track 3 preset susan output-lilypond
