#!/bin/sh
set -e
WHERE="/share/mirror/songsterr/stuff/d-keep/d-Nirvana/d-Smells Like Teen Spirit-s269/d-r413303/application_guitar_pro5-42928401.gp5"
DRUMMAP="44 hh 0,35 bd 1,43 toml 0,"
rm -f generated-*
LYRICS=`cat lyrics`
SCALE="c des d ees e f ges g aes a bes b"
java -jar ../../guitarproToLy/1.jar <"$WHERE" \
add-lyrics 0 1 "$LYRICS" \
drumMap "$DRUMMAP" \
markup-extra '\key f \minor' \
track 0 \
    preset kav \
    output-lilypond \
    output-lyrics \
    output-karaoke \
    which-lyrics arg \
track 0 \
    preset susan \
    output-lilypond \
track 1 \
    preset peter \
    output-lilypond \
    output-chords \
track 2 \
    preset peter \
    output-lilypond \
    output-dotext \
    output-chords \
track 3 \
    preset peter \
    output-lilypond \
    output-dotext \
track 4 \
    preset peter \
    output-lilypond \
    output-dotext \
track 5 \
    preset bass \
    output-lilypond \
    output-dotext \
track 6 \
    preset gg \
    output-drums \
2>&1|tee log
