#!/bin/sh
WHERE="application_guitar_pro3-15156060.gp3"
DRUMMAP="44 hh 0,48 tomh 0,47 tomml 0,41 toml 0,43 toml 0,40 sn 0,"
set -e
rm -f generated-*
LYRICS=`cat lyrics`
SCALE="c cis d dis e f fis g gis a bes b"
java -jar ../../guitarproToLy/1.jar <"$WHERE" \
add-lyrics 5 1 "$LYRICS" \
modified-filename drs \
markup-extra 0 '\key d \minor' \
scale "$SCALE" \
drumMap "$DRUMMAP" \
track 5 \
    preset kav \
    output-lilypond \
    output-lyrics \
    output-karaoke \
    output-dotext \
    which-lyrics arg \
track 5 \
    preset susan \
    output-lilypond \
    output-dotext \
track 3 \
    preset peter \
    output-lilypond \
    output-dotext \
track 4 \
    preset bass \
    output-lilypond \
track 0 \
    preset midiOne \
    output-lilypond \
track 1 \
    preset midiOne \
    output-lilypond \
track 2 \
    preset midiOne \
    output-lilypond \
track 6 \
    preset midiOne \
    output-lilypond \
track 7 \
    preset midiOne \
    output-lilypond \
track 8 \
    preset gg \
    output-drums \
2>&1|tee log
