#!/bin/sh
set -e
WHERE="a.gp5"
rm -f generated-*
LYRICS=`cat lyrics`
java -jar ../../guitarproToLy/1.jar <"$WHERE" \
add-lyrics 0 6 "$LYRICS" \
modified-filename drs \
track 0 \
    preset kav \
    which-lyrics arg \
    output-lilypond \
    output-lyrics \
    output-karaoke \
track 1 \
    preset susan \
    transpose 12 \
    output-lilypond \
track 2 \
    preset midiOne \
    output-lilypond \
track 3 \
    preset midiOne \
    output-lilypond \
track 4 \
    preset midiOne \
    output-lilypond \
track 5 \
    preset peter \
    output-dotext \
    output-lilypond \
track 6 \
    preset peter \
    output-lilypond \
track 7 \
    preset peter \
    output-dotext \
    output-lilypond \
track 8 \
    preset bass \
    output-lilypond \
track 9 \
    preset gg \
    output-drums \
2>&1|tee log
