#!/bin/sh
SONG=https://www.songsterr.com/a/wsa/the-police-message-in-a-bottle-tab-s3706t1

curl -s $(curl -s https://www.songsterr.com/api/meta/$(echo "$SONG" | sed -ne 's/^.*s\([0-9]*\)t[0-9]*$/\1/p')/revisions | sed -e 's/"source":"\([^"]*\)"/\
\1\
/g' | sed -ne 2p) | java -jar ../../guitarproToLy/1.jar \
markup-extra '\key cis \minor' \
track 0 preset kav output-lilypond output-lyrics \
track 1 preset peter output-lilypond \
track 3 preset bass output-lilypond \
track 4 preset gg output-drums

sed -e 's/gis8\\4/e8\\5/' < generated-guitar > tmp
mv tmp generated-guitar
