#!/bin/sh
WHERE="https://www.songsterr.com/a/wsa/f2e38040f1ef8b3f9e3b137e651bff55-f2e38040f1ef8b3f9e3b137e651bff55-tab-s474965"

java -jar ../../songsterrToLy/1.jar --name guitarPart --output-tabs "${WHERE}t0" >generated-guitartabs
java -jar ../../songsterrToLy/1.jar --name stringsPart --output-tabs "${WHERE}t1" >generated-stringstabs
java -jar ../../songsterrToLy/1.jar --name bassPart --output-tabs "${WHERE}t2" >generated-basstabs
java -jar ../../songsterrToLy/1.jar --name drumsPart "${WHERE}t3" >generated-drumscolors
java -jar ../../songsterrToLy/1.jar --name voPart --output-tabs "${WHERE}t4" >generated-votabs

# Usage: java SongsterrToLy [options] url
# url is something like https://www.songsterr.com/a/wsa/momoiro-clover-z-moon-pride-tab-s456232t0 or - for stdin.
# options:
# [--drumMap map]  Specify drum map.  Something like --drumMap "49 cymc 0,38 sn 0,36 bd 1"
# [--extra-stuff stuff]  Add extra stuff to output.
# [--lyrics]  Extract lyrics instead of notes.
# [--lyrics-in-voices]  Extract lyrics from voices instead of lyrics.
# [--name partName]  Specify partName.
# [--no-ghost-notes]  Don't include ghost notes.
# [--no-string-numbers]  Don't include string numbers.
# [--output-text]  Output text.
# [--output-relative]  Output \relative notes.
# [--output-tabs]  Output tabs instead of notes.
# [--scale scale]  Specify note spelling.  Something like --scale "c des eisis"
# [--shift n/d]  Shift notes right n/d beats.  Use --shift -21/5 to shift notes left 4 1/5th beat.
