#!/bin/bash
set -e -o pipefail
WHERE="/share/mirror/songsterr/stuff/d-keep/d-Babymetal/d-Gimme Choco-s392595/d-r397111/application_guitar_pro5-41439375.gp5"
SCALE=""
rm -f generated-*
java -jar ../../guitarproToLy/1.jar <"$WHERE" \
scale "$SCALE" \
track 7 \
    preset kav \
track 7 \
    preset lyrics \
track 6 \
    preset midiOne \
track 6 \
    name midiOne \
    midi-who midiOne \
    output-dotext \
track 4 \
    preset bass \
track 3 \
    preset midiTwo \
track 3 \
    name midiTwo \
    midi-who midiTwo \
    output-dotext \
track 2 \
    preset midiThree \
track 2 \
    name midiThree \
    midi-who midiThree \
    output-dotext \
track 1 \
    preset midiFour \
track 1 \
    name midiFour \
    midi-who midiThree \
    output-dotext \
track 0 \
    preset peter \
track 0 \
    name guitar \
    midi-who midiPeter \
    output-dotext \
track 5 \
    preset gg \
2>&1|tee log
