#!/bin/sh
set -e
rm -f generated-*
java -jar ../../1.jar <"/share/mirror/songsterr/stuff/d-keep/d-The Beatles/d-Don't Pass Me By-s61425/d-r77210/application_guitar_pro3-3677427.gp3" \
scale "" \
track 3 \
    preset kav \
    output-lilypond \
track 0 \
    preset kav \
    output-lyrics \
    output-karaoke \
track 2 \
    preset susan \
track 0 \
    preset peter \
    output-dotext \
track 4 \
    preset midiOne \
track 5 \
    preset midiTwo \
track 6 \
    preset bass \
    output-dotext \
track 7 \
    preset gg \
2>&1|tee log
