#!/bin/sh
WHERE="application_guitar_pro5-42273187.gp5"
DRUMMAP="41 toml 0,35 bd 1,"
set -e
rm -f generated-*
java -jar ../../guitarproToLy/1.jar <"$WHERE" \
markup-extra 0 '\key a \major' \
drumMap "$DRUMMAP" \
track 0 \
    preset kav \
    layout-extra '\clef "treble_8"' \
    output-lilypond \
    output-lyrics \
    output-karaoke \
track 0 \
    preset susan \
    transpose 12 \
    output-lilypond \
track 2 \
    preset peter \
    output-lilypond \
track 3 \
    preset bass \
    output-lilypond \
track 4 \
    preset gg \
    output-drums \
2>&1|tee log
