#!/bin/sh
set -e
WHERE="/share/mirror/songsterr/stuff/d-keep/d-The Eagles/d-Hotel California-s447/d-r414164/application_guitar_pro5-43011967.gp5"
DRUMMAP="35 bd 1,48 tomh 0,43 toml 0,41 toml 0,"
rm -f generated-*
java -jar ../../guitarproToLy/1.jar <"$WHERE" \
markup-extra '\key e \major' \
modified-filename vocals_karaoke \
drumMap "$DRUMMAP" \
track 0 \
    preset kav \
    output-lilypond \
    output-lyrics \
    output-karaoke \
track 0 \
    preset susan \
    output-lilypond \
track 1 \
    preset peter \
    output-chords \
    output-lilypond \
track 2 \
    preset peter \
    output-lilypond \
track 3 \
    preset peter \
    output-lilypond \
track 4 \
    preset peter \
    output-lilypond \
    output-dotext \
track 5 \
    preset peter \
    output-dotext \
    output-lilypond \
track 6 \
    preset peter \
    output-dotext \
    output-lilypond \
track 9 \
    preset peter \
    output-lilypond \
track 7 \
    preset bass \
    output-lilypond \
track 8 \
    preset gg \
    output-drums \
2>&1|tee log
