#!/bin/sh
WHERE="application_guitar_pro5-16160530.gp5"
set -e
rm -f generated-*
LYRICS=`cat lyrics`
java -jar ../../guitarproToLy/1.jar <"$WHERE" \
add-lyrics 3 1 "$LYRICS" \
markup-extra 0 '\key e \major' \
modified-filename drs \
track 3 \
    preset kav \
    output-lilypond \
    output-lyrics \
    output-karaoke \
    output-dotext \
    transpose "\transpose c c, " \
    layout-extra '\clef "treble_8"' \
track 1 \
    preset susan \
    output-lilypond \
track 2 \
    name lpiano \
    instrument-name Piano \
    instrument-short-name Pi \
    layout-who 'allPart susanPart' \
    layout-extra '\clef bass' \
    output-lilypond \
track 2 \
    preset midiOne \
    output-lilypond \
track 5 \
    preset midiOne \
    output-dotext \
    output-lilypond \
track 4 \
    preset peter \
    output-dotext \
    output-lilypond \
track 0 \
    preset bass \
    output-dotext \
    output-lilypond \
track 6 \
    preset gg \
    output-drums \
2>&1|tee log
