#!/bin/sh
WHERE=application_x_octet_stream-3628929.gp4
set -e
rm -f generated-*
DRUMMAP="43 tomml 0,41 toml 0,57 cymc 0,35 bd 1,"
java -jar ../../guitarproToLy/1.jar <"$WHERE" \
drumMap "$DRUMMAP" \
markup-extra 0 '\key a \major' \
track 2 \
    preset kav \
    layout-extra '\clef "treble_8"' \
    output-lilypond \
    output-lyrics \
    output-karaoke \
track 4 \
    preset susan \
    transpose 12 \
    output-lilypond \
track 0 \
    preset peter \
    output-lilypond \
track 1 \
    preset peter \
    output-lilypond \
track 3 \
    preset bass \
    output-lilypond \
track 5 \
    preset gg \
    output-drums \
2>&1|tee log
