#!/bin/sh
WHERE=application_guitar_pro5-43395305.gp5
set -e
rm -f generated-*
LYRICS=`cat lyrics`
java -jar ../../guitarproToLy/1.jar <"$WHERE" \
modified-filename drs \
markup-extra 0 '\key a \major' \
add-lyrics 0 1 "$LYRICS" \
track 0 \
    preset kav \
    layout-extra '\clef "treble_8"' \
    output-lilypond \
    output-lyrics \
    output-karaoke \
track 0 \
    preset susan \
    transpose 12 \
    output-lilypond \
track 1 \
    preset peter \
    output-lilypond \
track 2 \
    preset peter \
    output-lilypond \
track 3 \
    preset peter \
    output-lilypond \
track 6 \
    preset bass \
    output-lilypond \
track 4 \
    preset midiOne \
    output-lilypond \
track 5 \
    preset midiOne \
    output-lilypond \
track 7 \
    preset gg \
    output-drums \
2>&1|tee log
