#!/bin/sh
# https://www.songsterr.com/api/meta/9957/revisions
# https://d12drcwhcokzqv.cloudfront.net/3621084.gp4
java -jar ../../guitarproToLy/1.jar < song.gp5 \
markup-extra 0 '\key fis \minor' \
track 4 preset kav output-lilypond output-lyrics which-lyrics text \
track 0 preset peter output-lilypond \
track 2 preset bass output-lilypond \
track 6 preset gg output-drums \
track 7 preset susan output-lilypond output-lyrics which-lyrics text no-chords false \
track 1 preset midiOne output-lilypond \
track 3 preset midiTwo output-lilypond
