#!/bin/sh
# https://www.songsterr.com/api/meta/23039/revisions
# https://d12drcwhcokzqv.cloudfront.net/56863395.gp
java -jar ../../guitarproToLy/1.jar < song.gp5 \
markup-extra 0 '\key f \major' \
transpose 2 scale 'bes ees' \
track 1 preset kav output-lilypond output-lyrics which-lyrics text \
track 3 preset bass output-lilypond \
track 4 preset gg output-drums \
track 5 preset susan output-lilypond no-chords false output-lyrics which-lyrics text \
track 0 preset peter output-lilypond \
track 2 preset midiOne output-lilypond
