#!/bin/sh
# https://www.songsterr.com/api/meta/167/revisions
# https://d12drcwhcokzqv.cloudfront.net/59240392.gp
java -jar ../../guitarproToLy/1.jar < song.gp5 \
markup-extra 0 '\key a \major' \
track 3 preset kav output-lilypond output-lyrics which-lyrics text \
track 2 preset bass output-lilypond \
track 1 preset gg output-drums \
track 3 preset susan output-lilypond no-chords false output-lyrics which-lyrics text \
track 0 preset peter output-lilypond
