#!/bin/sh
set -e
rm -f generated-*
java -jar ../../1.jar <"/share/mirror/songsterr/stuff/d-keep/d-Bon Jovi/d-Wanted Dead Or Alive-s54/d-r331965/application_guitar_pro4-25940548.gp4" \
scale "" \
track 0 \
    preset peter \
track 0 \
    name guitar \
    midi-who midiPeter \
    output-dotext \
track 1 \
    preset peter \
    name guitarTwo \
    instrument-name Guitar2 \
    instrument-short-name Gtr2 \
track 2 \
    preset peter \
    name guitarThree \
    instrument-name Guitar3 \
    instrument-short-name Gtr3 \
track 2 \
    name guitarThree \
    midi-who midiPeter \
    output-dotext \
track 3 \
    preset peter \
    name guitarFour \
    instrument-name Guitar4 \
    instrument-short-name Gtr4 \
track 3 \
    name guitarFour \
    midi-who midiPeter \
    output-dotext \
track 4 \
    preset midiOne \
track 5 \
    preset bass \
track 6 \
    preset gg \
2>&1|tee log
