#!/bin/sh
java -jar ../../songsterrToLy/1.jar --name guitarPart --extra-stuff "% scale c des d ees e f ges g aes a bes ces'" --output-tabs "https://www.songsterr.com/a/wsa/kikis-delivery-service-rouge-message-tab-s466434t0" >generated-guitartabs
java -jar ../../songsterrToLy/1.jar --name pianoPart --no-string-numbers "https://www.songsterr.com/a/wsa/kikis-delivery-service-rouge-message-tab-s466434t0" >generated-piano
