#!/bin/sh
java -jar ../../guitarproToLy/1.jar < song.gp5 \
markup-extra 0 '\key d \major' \
track 0 preset peter output-lilypond \
track 1 preset susan output-lilypond \
track 2 preset bass output-lilypond \
track 3 preset gg output-drums \
track 4 preset kav layout-extra '\clef "treble_8"' output-lilypond output-lyrics output-karaoke
