#!/bin/sh
set -e
rm -f generated-*
java -jar ../../1.jar <"/share/mirror/ultimateguitar/stuff/d-keep/d-Momoiro Clover Z/d-Mouretsu Uchuu Koukyoukyoku Dai Nana Gakushou - Mugen No Ai/application_octet_stream-Guitar Pro 1682976 2014-11-24 00:17:16 download" \
scale "" \
track 6 \
    preset kav \
    which-lyrics "0" \
    output-lilypond \
    output-dotext \
    output-lyrics \
    output-karaoke \
track 6 \
    preset kav \
    output-lyrics \
    output-karaoke \
    which-lyrics "1,2" \
track 0 \
    preset peter \
    output-dotext \
    output-lilypond \
track 1 \
    preset peter \
    output-dotext \
    output-lilypond \
track 2 \
    preset peter \
    output-dotext \
    output-lilypond \
track 3 \
    preset peter \
    output-dotext \
    output-lilypond \
track 4 \
    preset bass \
    output-lilypond \
track 7 \
    preset midiOne \
    output-lilypond \
track 8 \
    preset midiOne \
    output-dotext \
    output-lilypond \
track 9 \
    preset midiOne \
    output-dotext \
    output-lilypond \
track 10 \
    preset midiOne \
    output-dotext \
    output-lilypond \
track 5 \
    preset gg \
    output-drums \
2>&1|tee log
