#!/bin/sh
set -e
rm -f generated-*
java -jar ../../1.jar <"/share/mirror/ultimateguitar/stuff/d-keep/d-Momoiro Clover Z/d-Mouretsu Uchuu Koukyoukyoku Dai Nana Gakushou - Mugen No Ai/application_octet_stream-Guitar Pro 1682976 2014-11-24 00:17:16 download" \
scale "" \
track 6 \
    preset kav \
    output-lilypond \
    output-dotext \
track 0 \
    preset kav \
    output-lyrics \
    output-karaoke \
track 0 \
    preset peter \
    output-dotext \
track 1 \
    preset peter \
    name guitarTwo \
    instrument-name Guitar2 \
    instrument-short-name Gtr2 \
    output-dotext \
track 2 \
    preset peter \
    name guitarThree \
    instrument-name Guitar3 \
    instrument-short-name Gtr3 \
    output-dotext \
track 3 \
    preset peter \
    name guitarFour \
    instrument-name Guitar4 \
    instrument-short-name Gtr4 \
    output-dotext \
track 4 \
    preset bass \
track 7 \
    preset midiOne \
track 8 \
    preset midiTwo \
    output-dotext \
track 9 \
    preset midiThree \
    output-dotext \
track 10 \
    preset midiFour \
    output-dotext \
track 5 \
    preset gg \
2>&1|tee log
