#!/bin/sh
set -e
if test '!' -f "buildBin"
then
    echo "Wrong directory"
    exit 1
fi
rm -rf /share/music/mp3/*.mp3 /share/music/pdf/*.pdf /share/music/robot/*.midi
for a in */music
do
    name=`dirname "$a"`
    if test "x$name" '!=' "xbin"
    then
	cd "$name"
	../buildBin
	cd ..
    fi
done
