#!/bin/bash
set -e
exec 2>&1
pwd=`pwd`
name=`basename "$pwd"`
cd ..
if test '!' -f build1
then
    echo 'Wrong directory'
    exit 1
fi
PARTS="$*"
rm -rf bin
mkdir -p bin/bin
cd bin
cp -l ../java/* .
javac -Xlint *.java
cd ..
cp -l *.i *.wav timidity_extra_silence.cfg bin
cp -l "$name"/* bin
cd bin
mv music music-if
mv header.i header.i-if
for a in *tabs
do
    if test -f "$a"
    then
	echo "$a"
	aa=`basename "$a" tabs`
	../tabsToLy.py <"$a" >"$aa"
    fi
done
for a in *colors
do
    if test -f "$a"
    then
	aa=`basename "$a" colors`
	../synesthesia.py <"$a" >"$aa"
    fi
done
for a in *text
do
    if test -f "$a"
    then
	../dotext.py <"$a" "${a}_"
    fi
done
for a in *.mp3
do
    if test -f "$a"
    then
	b=`basename "$a" .mp3`
	ffmpeg </dev/null -loglevel 16 -i "$a" "$b".wav
    fi
done
sed <music-if -n -e 's/^% ROBOT \(.*\)$/\1/p' >"bin/$name.robot"
for part in $PARTS
do
    for a in *-if
    do
	b=`basename "$a" -if`
	sed "s/^% IF $part //"  <"$a" >"$b"
    done
    if test "x$part" = "xmidi"
    then
	merge=
	for midi in midiCue midiGg midiPeter midiKav midiSusan midiKaraoke midiOne midiTwo midiThree midiFour
	do
	    cat <<EOF >"$name-$midi.ly"
\version "2.20.0"
\include "articulate.ly"
\include "header.i"
\include "music"
\score {
\unfoldRepeats \articulate \keepWithTag #'($midi keep) \removeWithTag #'(removeWithUnfold) \midimusic
\midi { }
}
EOF
	    lilypond -l WARN -o "$name-$midi" "$name-$midi.ly"
	    merge="$merge ${name@Q}-$midi.midi"
	done
	eval "java -cp . MergeMidi $merge >${name@Q}.midi"
	TIMIDITY_EXTRA_CFG="-c timidity_extra_silence.cfg"
	if test -f timidity_extra.cfg
	then
	    TIMIDITY_EXTRA_CFG="$TIMIDITY_EXTRA_CFG -c timidity_extra.cfg"
	fi
	timidity $TIMIDITY_EXTRA_CFG -OF -o "$name.flac" -A400 "$name.midi"
	ffmpeg </dev/null -loglevel 16 -i "$name.flac" "$name.mp3"
	cp "$name.midi" bin
	cp "$name.mp3" /share/music/mp3
	cp "$name.midi" "/share/music/midi/$name.midi"
    else
	n="${name}_$part"
	part1=`echo $part|sed 's/1/One/g;s/2/Two/g;s/3/Three/g;s/4/Four/g;s/5/Five/g;s/6/Six/g;s/7/Seven/g;s/8/Eight/g'`
	cat <<EOF >"$n.ly"
\version "2.20.0"
\include "header.i"
\include "music"
\score {
\keepWithTag #'(${part1}Part keep) \layoutmusic
\include "layout"
}
EOF
	lilypond -l WARN -o "$n" "$n.ly"
	cp "$n.pdf" bin
	cp "$n.pdf" /share/music/pdf
    fi
done
