#!/bin/sh
set -e
pwd=`pwd`
if test '!' -f "build1"
then
    echo "Wrong directory"
    exit 1
fi
rm -rf /share/music/mp3/*.mp3 /share/music/pdf/*.pdf /share/music/robot/*.midi
for a in */music
do
    name=`dirname "$a"`
    if test "x$name" '!=' "xbin"
    then
	PARTS=`grep '^% BIN ' "$a"|cut -c 7-`
	if test -n "$PARTS"
	then
	    cd "$name"
	    echo "$name"
	    ../build1 $PARTS
	    cd ..
	    for a in bin/bin/*
	    do
		b=`basename "$a"`
		case "$a" in
		    *.pdf)
			if test -f "../bin/$b"
			then
			    ./get_rid_of_id_in_pdf.py <"$a" >bin/1
			    ./get_rid_of_id_in_pdf.py <"../bin/$b" >bin/2
			    if cmp -s bin/1 bin/2
			    then
				continue
			    fi
			fi
			cp "$a" ../bin/
			;;
		    *)
			cp "$a" ../bin/
			;;
		esac
	    done
	fi
    fi
done
