#!/bin/sh
set -e
if test '!' -f "../buildBin"
then
    echo "Wrong directory.  Run this from one of src/*/ directories."
    exit 1
fi
pwd=`pwd`
name=`basename "$pwd"`
PARTS=`grep '^% BIN ' music|cut -c 7-`
if test -n "$PARTS"
then
    echo "$name"
    ../../build/build $PARTS
    cd ../../build
    mkdir -p ../bin/"$name"
    echo "name=$name" >bin/temp.aarin
    for a in bin/bin/*
    do
	b=`basename "$a"`
	case "$a" in
	    *.pdf)
		case "$b" in
		    *_gg.pdf)
			echo "default_pdf_file=../pdf/$b" >>bin/temp.aarin
			;;
		esac
		echo "pdf_file=../pdf/$b" >>bin/temp.aarin
		if test -f "../bin/$b"
		then
		    ./get_rid_of_id_in_pdf.py <"$a" >bin/1
		    ./get_rid_of_id_in_pdf.py <"../bin/$b" >bin/2
		    if cmp -s bin/1 bin/2
		    then
			touch ../bin/"$name/$b"
			continue
		    fi
		fi
		cp "$a" ../bin/"$name"
		;;
	    *.midi)
		echo "midi_file=../midi/$b" >>bin/temp.aarin
		cp "$a" ../bin/"$name"
		;;
	    *.robot)
		cat "$a" >>bin/temp.aarin
		;;
	esac
    done
    test -d /share/music && cp bin/temp.aarin "/share/music/aarin/$name.aarin"
fi
