#!/bin/sh
java -jar ../../songsterrToLy/1.jar --scale 'c des d ees e f ges g aes a bes b' --name vocals --no-string-numbers https://www.songsterr.com/a/wsa/john-lennon-gimme-some-truth-tab-s453786t0 > vocals
java -jar ../../songsterrToLy/1.jar --scale "c des d ees e f ges g aes a bes b" --name rguitar --output-tabs https://www.songsterr.com/a/wsa/john-lennon-gimme-some-truth-tab-s453786t1 > rguitartabs
java -jar ../../songsterrToLy/1.jar --scale 'c des d ees e f ges g aes a bes b' --name sguitar --output-tabs https://www.songsterr.com/a/wsa/john-lennon-gimme-some-truth-tab-s453786t2 > sguitartabs
java -jar ../../songsterrToLy/1.jar --scale 'c des d ees e f ges g aes a bes b' --name aguitar --output-tabs https://www.songsterr.com/a/wsa/john-lennon-gimme-some-truth-tab-s453786t3 > aguitartabs
java -jar ../../songsterrToLy/1.jar --scale 'c des d ees e f ges g aes a bes b' --name bass --output-tabs https://www.songsterr.com/a/wsa/john-lennon-gimme-some-truth-bass-tab-s453786t4 > basstabs
java -jar ../../songsterrToLy/1.jar --scale 'c des d ees e f ges g aes a bes b' --name drum https://www.songsterr.com/a/wsa/john-lennon-gimme-some-truth-drum-tab-s453786t5 | sed -e 's/[<]bda bda[>]/bd/g' -e 's/bda/bd/g' -e 's/64 sn16[.] r64/8/g' -e 's/sn16[.] r64//g' -e 's/bd64 r8[.] r32[.]/bd4/g' -e 's/cymcb/cymc/g' > drums
java -jar ../../songsterrToLy/1.jar --scale 'c des d ees e f ges g aes a bes b' --name gpiano --no-string-numbers https://www.songsterr.com/a/wsa/john-lennon-gimme-some-truth-tab-s453786t6 > gpiano
java -jar ../../songsterrToLy/1.jar --scale 'c des d ees e f ges g aes a bes b' --name epiano --no-string-numbers https://www.songsterr.com/a/wsa/john-lennon-gimme-some-truth-tab-s453786t7 > epiano
