#!/bin/sh
set -e
./build
for a in test/*.html
do
    b=`basename "$a" .html`
    d=`dirname "$a"`
    lyrics=
    if test "x$b" = "xlyrics"
    then
	lyrics="--lyrics"
    fi
    java -jar 1.jar $lyrics - <"$a" >"$d/$b.ly"
done
