#!/bin/sh
java -jar ../../guitarproToLy/1.jar < song.gp5 \
markup-extra 0 '\key g \major' \
track 4 preset kav output-lilypond output-lyrics which-lyrics text \
track 3 preset bass output-lilypond \
track 1 preset gg output-drums \
track 2 preset susan output-lilypond \
track 0 preset peter output-lilypond
